version: '3'
services:
  collector-microservice:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        SERVICE: collector
    ports:
      - "8080:8080"
  ingestor-microservice:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        SERVICE: ingestor
    ports:
      - "8082:8082"
