version: '3'
services:
  nodejs-backend:
    build:
      context: ./web/backend
    ports:
      - "8000:8000"
  log-collector-microservice:
    build:
      context: ./services/log-collector
    ports:
      - "8080:8080"
