version: '3'
services:
  nodejs-backend:
    build:
      context: ./web/backend
    ports:
      - "8000:8000"
  collector-microservice:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        SERVICE: collector
    ports:
      - "8080:8080"
  ingestor-microservice:
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        SERVICE: ingestor
    ports:
      - "8082:8082"
